# Generated by Django 4.1.2 on 2022-12-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noticeText', models.TextField(max_length=500, verbose_name='Текст заметки')),
                ('timeCreate', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'Поле заметки',
                'verbose_name_plural': 'Поля заметок',
                'ordering': ['id'],
            },
        ),
    ]
