# Generated by Django 4.0.4 on 2022-12-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='selectedDate',
            field=models.CharField(default=0, max_length=20, verbose_name='дата в календаре'),
            preserve_default=False,
        ),
    ]
